---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-core-middletier
spec:
  project: thoth-prod
  source:
    path: core/overlays/prod/middletier-prod
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    targetRevision: master
  destination:
    namespace: thoth-middletier-prod
    server: "https://api.ocp.prod.psi.redhat.com:6443"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
