---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-metrics-exporter
spec:
  project: thoth-prod
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: metrics-exporter/overlays/prod
    targetRevision: HEAD
  destination:
    server: 'https://api.ocp.prod.psi.redhat.com:6443'
    namespace: thoth-infra-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
